### ISSUE TITLE
Error message link should be on the word "zoonotify support" only 

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#1016]

**Comment by mahtabiltarabian** [comment]
<img width="1467" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45103170db1d6f03e1bddec902c117e572d0f780/image.png" alt="image.png" />
