### ISSUE TITLE
The Mouse over is rendering behind the CI span

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#1044]

**Comment by tasjacrease** [comment]
not fixed yet

**Comment by tasjacrease** [comment]
<img width="613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0h5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dd303626be076513f1262958ee109e69f5ab781/grafik.png" alt="grafik.png" />
