### ISSUE TITLE
As a user I would like to use the graphs on the prev page for presentation (high resolution, big fonts)

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#1116]
I would like to discuss the possibility to download graphs with higher resolution and with bigger fonts.

**Comment by tasjacrease** [comment]
@mahtabiltarabian The text in the graphs is still a bit small. Can we make it even bigger?

**Comment by mahtabiltarabian** [comment]
yes of curese, now please check this

**Comment by tasjacrease** [comment]
The layout of tge graph has changed when I download it. It does look abit squised now. We will need even better resolution of the plot. I would like to reopen the ticket therefore.
