### ISSUE TITLE
No graphs are generated when microogranism is changed on prev page

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#1127]
On prev page, when I change the selection of microorganims for the graphs, sometimes no graphs are generated, even though they should be there

![Image](https://github.com/user-attachments/assets/633d527e-c168-4a09-88ea-ea2410b21086)

**Comment by mahtabiltarabian** [comment]
I select all microorganism noww and i see all microorganism have hart in this : i think it is happend sometimes my be releted to delay in tetch data :::![Image](https://github.com/user-attachments/assets/ab949d3f-088c-48ec-9df9-485e6adcd60c)

**Comment by tasjacrease** [comment]
Ok, I can also not recreate the problem
