### ISSUE TITLE
Drop down list is truncated after search on prev page

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#1141]
I searched for campy on prevpage, then did data download and then tried to select more bacteria in the search section and only a truncated list of microorganisms was shown 

![Image](https://github.com/user-attachments/assets/8bc896fe-c9b7-44da-8d7d-453a400fc969)

**Comment by mahtabiltarabian** [comment]
I did same this senerio and i see other microorganism i think it was releted to delaz the server 

![Image](https://github.com/user-attachments/assets/6f2ffe3e-307c-4f22-9a77-6f60d3dd2487)

**Comment by mahtabiltarabian** [comment]
For me it is ok  agree whit you delay in server

![Image](https://github.com/user-attachments/assets/4978c248-9f9e-4b20-a42f-1c5c167956da)
