### ISSUE TITLE
Change header in export-files

### ISSUE THREAD

**Issue by MicheleK17** [SiLeBAT/zoonotify-client#116]
; for separation
space after :

**Comment by dptolle** [comment]
#Parameter:
"#Pathogens: Salmonella spp"
"#Food products: Hackfleisch vom Schwein"
#Project name: All values

The labels #Pathogen and #Food Products should not be in between the quotes

**Comment by dptolle** [comment]
Current output example:
#Parameter:
#Pathogens: "Salmonella spp"
#Food products: "Frisches Putenfleisch;Frisches Hähnchenfleisch"
#Project name: "All values"

Individual filter selections should be quoted, not the list of filter selections:

#Parameter:
#Pathogens: "Salmonella spp"
#Food products: "Frisches Putenfleisch";"Frisches Hähnchenfleisch"
#Project name: "All values"
