### ISSUE TITLE
On the explanation page of Prod under antibiotic resistance if I clik on a method/table nothing opens

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#1161]
It works well on dev (see picture)

![Image](https://github.com/user-attachments/assets/513094b3-a2b2-4932-b623-cdcac3a96c22)

**Comment by dptolle** [comment]
@tasjacrease @mahtabiltarabian This is a data issue.  All the entries in the Resistance_Table content type were still in unpublished 'Draft@ mode.  They need to be published to become available online.  I will do so now.
