### ISSUE TITLE
As a User I would like to apply filters to reduce the size of my dataset

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#29]
# Hauptfilter
Jahr
BL 
Erreger
Probenahmeort
Probenherkunft	
Tierart/Lebensmittel Oberkategorie	
Tierart Produktionsrichtung/Lebensmittel	
Matrix
AMR

# SubFilter
Probenahmegrund
Matrixdetail
Merkmale

# Unnecessary
Originaleinsendenr.
BfR_Isolat_Nr
NRL
ZoMo-Programm
Bericht-e

# Include
DB_ID
AMR Qualitative and quantitative

**Comment by MicheleK17** [comment]
Filter structure: 

- Main-Filter: 
> Erreger 
> Matrix
> Projektname / Probenahmegrund
> Bundesland
> Stufe der Lebensmittelgewinnung
> AMR

- Sub-Filter: 
> Typisierung ( MRSA_spa_Typ / Entero_Spez / Campy_Spez / Salm_Serovar / Listeria_Serotyp / STEC )

**Comment by dptolle** [comment]
# Hauptfilter
Jahr
BL 
Erreger
Probenahmeort
Probenherkunft	
Tierart/Lebensmittel Oberkategorie	
Tierart Produktionsrichtung/Lebensmittel	
Matrix
AMR

# SubFilter
Probenahmegrund
Matrixdetail
Merkmale

# Unnecessary
Originaleinsendenr.
BfR_Isolat_Nr
NRL
ZoMo-Programm
Bericht-e

# Include
DB_ID
AMR Qualitative and quantitative
