### ISSUE TITLE
As a user I would like to have the "Proleme-melden"-e-Mail filled with suppotive information

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#38]

**Comment by MicheleK17** [comment]
="mailto:mibi-portal@bfr.bund.de?subject=MiBi-Portal-Problem:&amp;body=Bitte schildern Sie uns Ihr Problem. Falls es Probleme mit einem hochgeladenen Probeneinsendebogen gab, hängen Sie diesen bitte an. Handelt es sich um ein Problem mit der Darstellung im MiBi-Portal, kann auch ein Screenshot hilfreich sein."
