### ISSUE TITLE
Refactor the component structure for the AMR value diaolog and download

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#601]

**Comment by mahtabiltarabian** [comment]
this task finished but when i want push my code i get error for type script  . for example table_id should be  change to tableId . for this we need change naming in the cms . I think we should speak  about this . but this task finished . 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--109f123bdaf1e7d0fe826586119d15c862959b3e/image.png)
