### ISSUE TITLE
Client version number not propergated correctly to production

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#764]

**Comment by mahtabiltarabian** [comment]
It is correct in the :https://zoonotify.bfr.berlin/<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ZxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b64b830574d5d327c45d2c26707c5afe0d650b6/msg670437278-133852.jpg" alt="msg670437278-133852.jpg" />
