### ISSUE TITLE
Create e2e tests to check for basic page availability

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#782]

**Comment by mahtabiltarabian** [comment]
<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelRxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd5092a6f97513578ec0b46a25b6ebc7c6fe93ed/image.png" alt="image.png" />
