### ISSUE TITLE
On the dev server: I cannot scroll on the explanation page and evaluation page to see all content.

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#809]
On the explanation page if I unfolde the background I cannot scroll to the bottom of the text (it works on the productive system).

On the evaluation page I cannot scroll to the bottom of the text that explains how to filter (it works on the productive system).

**Comment by mahtabiltarabian** [comment]
i updated explanation page but  auto scroll in evaluation page working correctly
<img width="509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2RBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed00ce5e1eba67da291b4801f4f09cc6cf246ba9/image.png" alt="image.png" />

**Comment by mahtabiltarabian** [comment]
I updated explanation page but  auto scroll work correctly in  evaluation page,,,

**Comment by tasjacrease** [comment]
Hi @mahtabiltarabian , I checked the scroll on my laptop today and I still have the same problem. I cannot scroll to the bottom of the "Anleitung" on the evaluation page on dev. See attached screen shot. I can't get further down on the left panel. <img width="1568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5262ab1f036530c1b2c4dffac68d746010f2e80b/20240409_ZooNotify_scroll_problem.PNG" alt="20240409_ZooNotify_scroll_problem.PNG" />

**Comment by tasjacrease** [comment]
The footer seems to be covering the bottom of the "Anleitung" / "Instructions" part of eavluation. Can we adapt this`?

**Comment by mahtabiltarabian** [comment]
yes i will do that.
