### ISSUE TITLE
As a user a find it a bit confusing that I have to click (somewhere on the page) once I finish filtering. Could we have an OK and Canbel button instead?

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#811]
An example of what I mean can be seen in the screenshot below or here: https://www.efsa.europa.eu/en/microstrategy/salmonella-dashboard

Got to the sub-page "Total untits tested of major fodd category" then check filter for food category as an example

<img width="1085" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEpBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8837964e5e451eb3a797ef7840ad849c9f10bee5/EFSA_filter.PNG" alt="EFSA_filter.PNG" />

An even nicer example can be seen on the BVl portal. Check the attached screenshot or here: https://gis.bvl.bund.de/
The select "Gast-Zugang", then "Zoonosen-Monitoring Dashboard", then "Zooosen_Monitoring Prävalenzen" --> "Hauptfilter" and look at the "Tierart/Matrix" filter window that opens. It seems very complex, so I understand if we can't implement something like it. I just wanted to show it, 

<img width="905" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzVBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5dd2dd3e5d3313145e5ee36905823efe082eaa85/BVL_filter.PNG" alt="BVL_filter.PNG" />

**Comment by mahtabiltarabian** [comment]
there is Icon for open and close . we can explain it in the evaluation information)

**Comment by tasjacrease** [comment]
Can we make the Icon to open and close the filter a bit bigger maybe to make it more clear?

**Comment by dptolle** [comment]
Icon exists - following Material design standards
