### ISSUE TITLE
As a user I would like to have a question mark icon next to each filter with a mouse over that contains an explanation of each filter

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#821]
I will provide text for the mouse over.

**Comment by tasjacrease** [comment]
I couldn't find a question mark, but an exclamation mark. They have it on the EFSA dashboards. Here a link: https://www.efsa.europa.eu/en/microstrategy/campylobacter-dashboard

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL09RQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03b3b46631311b6a98105429103cd8cf47888517/grafik.png" alt="grafik.png" />

**Comment by tasjacrease** [comment]
Unfortunately, I cannot add content. Maybe I am doing something wrong?

**Comment by mahtabiltarabian** [comment]
After restart CMS this issue solved,
