### ISSUE TITLE
As a content manager, I would like to be able to add example figures to the "Graphiken" Section on the explanation page

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#823]

**Comment by tasjacrease** [comment]
I added a graph through cms, but unfortunately it is way too big. Can I adjust the size somehow? See screenshot.

<img width="1303" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--111582053c7edeb0df0cd627d5e450f0adb5d321/grafik.png" alt="grafik.png" />

**Comment by tasjacrease** [comment]
This is the figure I would like to add to the Trendgraph section in explanations. 

<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0tSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b453add122c24ac93aacff535635edbe440f6643/1_Huhn_6_EC_4_Trend_Diagramm_Hp_Ci_WHO_Masthaehnchen_Frisches_Fleisch_P33_EC_xlsx_c7904c9a5b.jpg" alt="1_Huhn_6_EC_4_Trend_Diagramm_Hp_Ci_WHO_Masthaehnchen_Frisches_Fleisch_P33_EC_xlsx_c7904c9a5b.jpg" />

**Comment by mahtabiltarabian** [comment]
I checked it , it is depend  your figures size, for example ,I resize your figures and then upload this , this is ok. 
<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d795dc257a8449927d6fab4a30f9dda4142813b/image.png" alt="image.png" />

**Comment by tasjacrease** [comment]
Ok. Thank you for checking. I will do that then.

**Comment by mahtabiltarabian** [comment]
your welcome dear,

**Comment by tasjacrease** [comment]
I have added the figure to both the German and English Explanation page. Unfortunately the resolution is not great due to resizing, but I think it is ok.
