### ISSUE TITLE
As a User I want to have my selected search parameters for the prevalence search displayed in the main content window

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#826]

**Comment by tasjacrease** [comment]
I am not sure if I understand this ticket correctly. For me only the selected microorganism is shown under "parameter" but not the other things I have selected for e.g. Probenursprung, Matrix, and Probennahmestelle

**Comment by mahtabiltarabian** [comment]
This ticket was for parameter in microorganism because before we have just microorganism, you can create tickets for sample origin  and thicket for matrix and sampling stage , we will do this
