### ISSUE TITLE
uniq ID for sample origin in prevalence  should update to name

### ISSUE THREAD

**Issue by mahtabiltarabian** [SiLeBAT/zoonotify-client#847]

**Comment by mahtabiltarabian** [comment]
ID change to name

<img width="776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--208ced730c65ce839d18554fdc5f275acf1d0c85/image.png" alt="image.png" />

**Comment by tasjacrease** [comment]
@dptolle I don't think I can check this
