### ISSUE TITLE
As a User I want to be able to download the prevalence data I have selected using the existing filters

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#853]
Add a download button to the Table controls panel

**Comment by mahtabiltarabian** [comment]
<img width="1807" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHl2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b11450d2b52652c248cb0c33133dc458ab45bd4/image.png" alt="image.png" />

**Comment by tasjacrease** [comment]
This is great! Thank you!!!  I the downloaded table, can we have the same order of columns as in the table on the website? And we don't need the column further details. It also seems that when I load the csv locally that it has problems with ü and ä. Can we fix that?
