### ISSUE TITLE
On the prevalence page, move the download button for the data table to the bottom of the table

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#882]

**Comment by mahtabiltarabian** [comment]
<img width="1513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelh2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec497102b2cbf2ca22e0beda8f5c8b37216d122a/image.png" alt="image.png" />
