### ISSUE TITLE
The data in the prevalence data table should only be shown once attributes for mandatory filters are selected. The mandatory filters should be year, microorganism and sample origin.

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#897]
No data should be loaded in the data table on the prevalence page when the page is opened. Only once the mandatory filters (year, microorganism and sample origin) are selected the data should be loaded.

We should also somehowlet the user know that year, microorganism and sample origin are defined as mandatory filters. Maybe we can highlight the filter fields somehow. I will think about it.

**Comment by mahtabiltarabian** [comment]
Hi tasja, 
"We have decided that for this ticket, a star will be placed next to each box to indicate that it is required. The user must select these three boxes, and only then will the search button become active. The remaining boxes are optional."

**Comment by tasjacrease** [comment]
Sounds good to me. Thank you

**Comment by tasjacrease** [comment]
@mahtabiltarabian Thank you very much. This is great. I am not sure about the position of the star. I would suggest that we discuss this during our next meeting.
