### ISSUE TITLE
As a content manager, I would like that the example graphs I added to the explanations page on dev are also shown on productive, when it is updated

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#948]

**Comment by dptolle** [comment]
@tasjacrease You should be able to  add them yourself.  Data migration from QA to Production was an issue that was poorly implemented this release and is on my list of things to discuss during our Release Post-Mortem next Monday (before or after or part of the Zoonotify Review)

**Comment by tasjacrease** [comment]
@dptolle it is not crucial for now. But as you said, it would be nice if it could just be taken from dev to production instead of me having to manage content in 4 places (dev/prod and en/de)

**Comment by dptolle** [comment]
We will write a wiki entry detailing what content is managed how and where.
