### ISSUE TITLE
As a user, when I open the filter on the evaluations page, I would like the scroll to be at the top by default and not at the bottom (see image)

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#949]
<img width="1693" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemhYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4308f0be3a1966d0ee394746140bbb48c9a541f0/grafik.png" alt="grafik.png" />

**Comment by mahtabiltarabian** [comment]
Hi Tasja,
before selcting the scroll is top . after select all options scroll put in the button , in evaluation page defult is select all it is reason for button scroll , 
![image](https://github.com/SiLeBAT/zoonotify-client/assets/77792173/53c4f6a3-5e14-4cf8-86b3-5817f3ae9a96)

**Comment by tasjacrease** [comment]
Hi Mahtab, let's discuss this in the next meeting and see what the others say. I think the top would be better when it is opened
