### ISSUE TITLE
Link to API documentation is not working on Prod

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#956]
Should be included in the hotfix

**Comment by mahtabiltarabian** [comment]
export const API_DOCUMENTATION_URL = "https://zoonotify.bfr.berlin"+ `/cms/documentation/v2.2.0`;  
I think we should use this  because export const API_DOCUMENTATION_URL = CMS_BASE_ENDPOINT + `/cms/documentation/v2.2.0`;       dont work in local,
