### ISSUE TITLE
the user can not select some years in sampling year  now it is work for  one or all , 

### ISSUE THREAD

**Issue by mahtabiltarabian** [SiLeBAT/zoonotify-client#986]

**Comment by tasjacrease** [comment]
I can still not select a year
<img width="344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21pQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0638f461c57cddf2a91b783ac463bfb2f0f84936/grafik.png" alt="grafik.png" />
